"""
ROSClaw CLI - Command Line Interface

Entry point for the `rosclaw` command.

Commands:
    rosclaw --version          Show version
    rosclaw init [DIR]         Initialize a ROSClaw workspace
    rosclaw run                Start the ROSClaw runtime
    rosclaw start              Alias for run (legacy)
    rosclaw status             Show runtime status
"""

import argparse
import sys
from pathlib import Path


def _version() -> str:
    from rosclaw import __version__

    return __version__


def cmd_init(args: argparse.Namespace) -> int:
    """Initialize a ROSClaw workspace."""
    target = Path(args.dir).resolve()
    target.mkdir(parents=True, exist_ok=True)

    config_path = target / "rosclaw.yaml"
    if config_path.exists() and not args.force:
        print(f"[ROSClaw] Workspace already exists: {target}")
        print("[ROSClaw] Use --force to overwrite config")
        return 1

    config_content = """# ROSClaw Workspace Configuration
# Generated by `rosclaw init`

robot_id: rosclaw_bot
safety_level: MODERATE

# Robot model (e-URDF or MuJoCo XML)
robot_model_path: ""

# Module toggles
enable_firewall: true
enable_memory: true
enable_practice: true
enable_swarm: false

# LLM Provider
llm:
  provider: deepseek
  model: deepseek-chat
  # api_key: set via ROSCLAW_API_KEY env var

# Practice / Timeline
practice:
  output_dir: ./practice_data
  auto_record: true

# SeekDB
memory:
  backend: memory
  # backend: sqlite
  # db_path: ./rosclaw.db
"""
    config_path.write_text(config_content, encoding="utf-8")

    # Create subdirectories
    (target / "practice_data").mkdir(exist_ok=True)
    (target / "skills").mkdir(exist_ok=True)
    (target / "models").mkdir(exist_ok=True)

    print(f"[ROSClaw] Initialized workspace: {target}")
    print(f"[ROSClaw] Config: {config_path}")
    print("[ROSClaw] Next: edit rosclaw.yaml, then run `rosclaw run`")
    return 0


def cmd_run(args: argparse.Namespace) -> int:
    """Start the ROSClaw runtime."""
    from rosclaw.core import Runtime, RuntimeConfig

    config = RuntimeConfig(
        robot_id=args.robot_id,
        robot_model_path=args.model_path,
        enable_firewall=args.firewall,
        enable_memory=args.memory,
        enable_practice=args.practice,
        enable_swarm=args.swarm,
    )

    runtime = Runtime(config)

    try:
        runtime.initialize()
        runtime.start()

        print(f"\n[ROSClaw] Runtime started for robot: {args.robot_id}")
        print("[ROSClaw] Press Ctrl+C to stop\n")

        import time

        while runtime.is_running:
            time.sleep(1)

    except KeyboardInterrupt:
        print("\n[ROSClaw] Shutdown requested...")
    finally:
        runtime.stop()

    return 0


def cmd_status(_args: argparse.Namespace) -> int:
    """Show ROSClaw runtime status."""
    import importlib

    config_path = Path("rosclaw.yaml")
    has_config = config_path.exists()

    # Module health checks
    modules = {
        "core.runtime": "Runtime",
        "core.event_bus": "EventBus",
        "firewall.validator": "FirewallValidator",
        "memory.interface": "MemoryInterface",
        "practice.recorder": "PracticeRecorder",
        "sandbox.runtime_adapter": "SandboxRuntimeAdapter",
        "how.engine": "HeuristicEngine",
    }

    health = []
    for mod_name, cls_name in modules.items():
        try:
            mod = importlib.import_module(f"rosclaw.{mod_name}")
            getattr(mod, cls_name)
            health.append((mod_name, "HEALTHY"))
        except (ImportError, AttributeError):
            health.append((mod_name, "DEGRADED"))

    # Overall status
    degraded = [m for m, s in health if s == "DEGRADED"]
    overall = "HEALTHY" if not degraded else "DEGRADED"

    # Output
    print("=" * 50)
    print("ROSClaw v1.0 Status")
    print("=" * 50)
    print(f"Config file:  {'found' if has_config else 'missing'} ({config_path})")
    print(f"Overall:      {overall}")
    print("-" * 50)
    print("Modules:")
    for mod_name, status in health:
        icon = "OK" if status == "HEALTHY" else "DEGRADED"
        print(f"  [{icon}] {mod_name:<30} {status}")
    print("=" * 50)

    if degraded:
        print(f"\nDegraded modules ({len(degraded)}): {', '.join(degraded)}")
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        prog="rosclaw",
        description="ROSClaw - Universal OS for Software-Defined Embodied AI",
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s {_version()}",
    )
    subparsers = parser.add_subparsers(dest="command")

    # init
    init_parser = subparsers.add_parser("init", help="Initialize a ROSClaw workspace")
    init_parser.add_argument("dir", nargs="?", default=".", help="Target directory")
    init_parser.add_argument("--force", action="store_true", help="Overwrite existing config")

    # run / start
    for name in ("run", "start"):
        run_parser = subparsers.add_parser(name, help="Start ROSClaw runtime")
        run_parser.add_argument("--robot-id", default="rosclaw_default", help="Robot identifier")
        run_parser.add_argument("--model-path", default=None, help="Path to robot model file")
        run_parser.add_argument(
            "--firewall", action="store_true", default=True, help="Enable Digital Twin Firewall"
        )
        run_parser.add_argument(
            "--memory", action="store_true", default=True, help="Enable Memory module"
        )
        run_parser.add_argument(
            "--practice", action="store_true", default=True, help="Enable Practice recorder"
        )
        run_parser.add_argument(
            "--swarm", action="store_true", default=False, help="Enable Swarm coordination"
        )

    subparsers.add_parser("status", help="Show runtime status")

    args = parser.parse_args()

    if args.command == "init":
        return cmd_init(args)
    elif args.command in ("run", "start"):
        return cmd_run(args)
    elif args.command == "status":
        return cmd_status(args)
    else:
        parser.print_help()
        return 1


if __name__ == "__main__":
    sys.exit(main())
